name: dager-macos
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.3.*
  - torchvision=0.18.*
  - torchaudio=2.3.*
  - numpy=1.26.*
  - scipy=1.13.*
  - pandas=2.2.*
  - scikit-learn=1.5.*
  - nltk=3.8.*
  - datasets=2.19.*
  - dill=0.3.8
  - evaluate
  - fsspec=2024.3.1
  - multiprocess=0.70.16
  - pyarrow=14.0.*
  - tqdm
  - pyyaml
  - pillow
  - psutil
  - filelock
  - requests
  - aiohttp
  - future
  - gitpython
  - boto3
  - importlib_resources
  - neptune-client
  - tokenizers=0.19.1
  - transformers=4.40.1
  - huggingface_hub=0.23.*
  - safetensors
  - sentencepiece
  - ffmpeg
  - pip:
      - rouge-score==0.1.2
      - accelerate==0.34.2
      - peft==0.13.0